package controllers

import (
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/manicar2093/expenses_api/internal/auth"
	"github.com/manicar2093/expenses_api/pkg/apperrors"
	"github.com/manicar2093/goption"
)

type (
	LoginController struct {
		auth.TokenRefreshable
		auth.LoginableByToken
		group *echo.Group
	}
	LoginToken struct {
		Token string `json:"token"`
	}
)

func NewLoginController(googleAuth auth.LoginableByToken, tokenRefreshable auth.TokenRefreshable, e *echo.Echo) *LoginController {
	controller := &LoginController{LoginableByToken: googleAuth, TokenRefreshable: tokenRefreshable, group: e.Group("/auth")}
	controller.register()
	return controller
}

func (c *LoginController) register() {
	c.group.POST("/login/google", c.LoginWGoogle)
	c.group.PUT("/refresh_token", c.RefreshToken)
}

// @Summary     Creates a new session by token
// @Description Creates a new session by token
// @Tags        login google
// @Accept      json
// @Produce     json
// @Param       google_token body     string           true "Token generated by google oauth"
// @Success     200          {object} auth.LoginOutput "Access information"
// @Failure     500          "Something unidentified has occurred"
// @Router      /auth/login/google [post]
func (c *LoginController) LoginWGoogle(ctx echo.Context) error {
	log.Infoln("Login requested!")
	var request auth.LoginInput
	if err := ctx.Bind(&request); err != nil {
		return apperrors.CreateResponseFromError(ctx, err)
	}
	request.ClientIP = getIP(ctx.Request())
	request.UserAgent = ctx.Request().UserAgent()
	loginRes, err := c.Login(ctx.Request().Context(), &request)
	if err != nil {
		return apperrors.CreateResponseFromError(ctx, err)
	}

	return ctx.JSON(http.StatusOK, loginRes)
}

// @Summary     Creates a new access token by session token
// @Description Creates a new access token by session token
// @Tags        refresh token
// @Accept      json
// @Produce     json
// @Param       session_refresh body     auth.RefreshTokenInput true "Session info"
// @Success     200             {object} auth.LoginOutput       "Access information"
// @Failure     500             "Something unidentified has occurred"
// @Router      /auth/refresh_token [put]
func (c *LoginController) RefreshToken(ctx echo.Context) error {
	log.Infoln("Refresh token requested!")
	var refreshToken auth.RefreshTokenInput
	if err := ctx.Bind(&refreshToken); err != nil {
		return apperrors.CreateResponseFromError(ctx, err)
	}
	refreshToken.ClientIP = getIP(ctx.Request())
	refreshToken.UserAgent = ctx.Request().UserAgent()

	refreshTokenRes, err := c.TokenRefreshable.RefreshToken(ctx.Request().Context(), &refreshToken)
	if err != nil {
		return apperrors.CreateResponseFromError(ctx, err)
	}

	return ctx.JSON(http.StatusOK, refreshTokenRes)
}

func getIP(r *http.Request) string {
	forwarded := goption.Of(r.Header.Get("X-FORWARDED-FOR"))
	if forwarded.IsPresent() {
		return forwarded.MustGet()
	}
	return r.RemoteAddr
}
