run:
  skip-dirs:
    - mocks
  skip-files:
    - ".*_test.go$"
  go: "1.18"

linters:
  enable:
    - funlen
    - ifshort
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - ireturn
    - testpackage
    - varnamelen
    - wastedassign
    - whitespace
