definitions:
  auth.LoginOutput:
    properties:
      access_token:
        type: string
      access_token_expires_at:
        type: string
      user:
        $ref: '#/definitions/auth.UserData'
        description: |-
          RefreshToken          string    `json:"refresh_token,omitempty"`
          RefreshTokenExpiresAt time.Time `json:"refresh_token_expires_at,omitempty"`
    type: object
  auth.UserData:
    properties:
      avatar:
        type: string
      email:
        type: string
      name:
        type: string
    type: object
  controllers.HealthCheckOutput:
    properties:
      db_status:
        type: string
      version:
        type: string
    type: object
  entities.Expense:
    properties:
      amount:
        type: number
      created_at:
        type: string
      day:
        type: integer
      description:
        $ref: '#/definitions/null.String'
      id:
        type: string
      is_paid:
        type: boolean
      month:
        type: integer
      name:
        $ref: '#/definitions/null.String'
      recurrent_expense:
        $ref: '#/definitions/entities.RecurrentExpense'
      recurrent_expense_id:
        $ref: '#/definitions/uuid.NullUUID'
      updated_at:
        type: string
      user:
        $ref: '#/definitions/entities.User'
      user_id:
        type: string
      year:
        type: integer
    type: object
  entities.RecurrentExpense:
    properties:
      amount:
        type: number
      created_at:
        type: string
      description:
        $ref: '#/definitions/null.String'
      expenses:
        items:
          $ref: '#/definitions/entities.Expense'
        type: array
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
      user:
        $ref: '#/definitions/entities.User'
      user_id:
        type: string
    type: object
  entities.User:
    properties:
      avatar:
        $ref: '#/definitions/null.String'
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      lastname:
        $ref: '#/definitions/null.String'
      name:
        $ref: '#/definitions/null.String'
      updated_at:
        type: string
    type: object
  expenses.CreateExpenseInput:
    properties:
      amount:
        type: number
      description:
        type: string
      for_next_month:
        type: boolean
      name:
        type: string
      user_id:
        type: string
    required:
    - amount
    - name
    type: object
  expenses.SetExpenseToPaidInput:
    properties:
      id:
        type: string
    type: object
  expenses.ToggleExpenseIsPaidInput:
    properties:
      id:
        type: string
    type: object
  expenses.ToggleExpenseIsPaidOutput:
    properties:
      current_is_paid_status:
        type: boolean
      id:
        type: string
    type: object
  expenses.UpdateExpenseInput:
    properties:
      amount:
        type: number
      description:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  null.String:
    properties:
      string:
        type: string
      valid:
        description: Valid is true if String is not NULL
        type: boolean
    type: object
  recurrentexpenses.CreateRecurrentExpenseInput:
    properties:
      amount:
        type: number
      description:
        type: string
      name:
        type: string
      user_id:
        type: string
    required:
    - amount
    - name
    type: object
  uuid.NullUUID:
    properties:
      uuid:
        type: string
      valid:
        description: Valid is true if UUID is not NULL
        type: boolean
    type: object
  validator.ValidationError:
    properties:
      errors: {}
    type: object
info:
  contact: {}
  title: Expenses API
  version: "1.0"
paths:
  /auth/login/google:
    post:
      consumes:
      - application/json
      description: Creates a new session by token
      parameters:
      - description: Token generated by google oauth
        in: body
        name: google_token
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Access information
          schema:
            $ref: '#/definitions/auth.LoginOutput'
        "500":
          description: Something unidentified has occurred
      summary: Creates a new session by token
      tags:
      - login google
  /expenses:
    post:
      consumes:
      - application/json
      description: Register a expense into the database
      parameters:
      - description: Expense to be created
        in: body
        name: expense_to_create
        required: true
        schema:
          $ref: '#/definitions/expenses.CreateExpenseInput'
      produces:
      - application/json
      responses:
        "201":
          description: Expense has been created
          schema:
            $ref: '#/definitions/entities.Expense'
        "400":
          description: When a request does not fulfill need data
          schema:
            $ref: '#/definitions/validator.ValidationError'
        "500":
          description: Something unidentified has occurred
      security:
      - ApiKeyAuth: []
      summary: Create an expense
      tags:
      - expenses
  /expenses/to_paid:
    put:
      consumes:
      - application/json
      description: Change a expense is_paid status
      parameters:
      - description: ID to change to is paid
        in: body
        name: expense_id
        required: true
        schema:
          $ref: '#/definitions/expenses.SetExpenseToPaidInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: When a request does not fulfill need data
          schema:
            $ref: '#/definitions/validator.ValidationError'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Set expense to paid
      tags:
      - expenses
  /expenses/toggle_is_paid:
    put:
      consumes:
      - application/json
      description: Toggle is paid status from an expense
      parameters:
      - description: ID to toggle is paid status
        in: body
        name: expense_id
        required: true
        schema:
          $ref: '#/definitions/expenses.ToggleExpenseIsPaidInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/expenses.ToggleExpenseIsPaidOutput'
        "400":
          description: When a request does not fulfill need data
          schema:
            $ref: '#/definitions/validator.ValidationError'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Toggle is paid status from an expense
      tags:
      - expenses
  /expenses/update:
    put:
      consumes:
      - application/json
      description: Updates an expense data depending if it is recurrent or not
      parameters:
      - description: ID to toggle is paid status
        in: body
        name: expense_update_data
        required: true
        schema:
          $ref: '#/definitions/expenses.UpdateExpenseInput'
      produces:
      - application/json
      responses:
        "200":
          description: Expense was updated
        "400":
          description: When a request does not fulfill need data
          schema:
            $ref: '#/definitions/validator.ValidationError'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Updates an expense
      tags:
      - expenses
  /health_check:
    get:
      description: It does a ping to db and returns service version
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/controllers.HealthCheckOutput'
        "424":
          description: Failed Dependency
          schema:
            $ref: '#/definitions/controllers.HealthCheckOutput'
        "500":
          description: Internal Server Error
      summary: Checks service health
      tags:
      - healt check
  /recurrent_expenses:
    post:
      consumes:
      - application/json
      description: Register into db a recurrent expense
      parameters:
      - description: Recurrent Expense
        in: body
        name: recurrent_expense
        required: true
        schema:
          $ref: '#/definitions/recurrentexpenses.CreateRecurrentExpenseInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: When a request does not fulfill need data
          schema:
            $ref: '#/definitions/validator.ValidationError'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Create a recurrent expense
      tags:
      - recurrent expenses
  /recurrent_expenses/all:
    get:
      description: Finds all recurrent expenses registered in db
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Get all recurrent expense
      tags:
      - recurrent expenses
  /recurrent_expenses/monthly_expenses:
    post:
      description: Register expenses from all recurrent expenses for current month
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Create expenses from all recurrent expenses into db
      tags:
      - recurrent expenses
  /reports/current_month:
    get:
      description: Generates current month general details
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Get current month details
      tags:
      - reports
securityDefinitions:
  ApiKeyAuth:
    description: Type "Bearer" and then your API Token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
