// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	recurrentexpenses "github.com/manicar2093/expenses_api/internal/recurrentexpenses"
	mock "github.com/stretchr/testify/mock"
)

// CreateMonthlyRecurrentExpenses is an autogenerated mock type for the CreateMonthlyRecurrentExpenses type
type CreateMonthlyRecurrentExpenses struct {
	mock.Mock
}

type CreateMonthlyRecurrentExpenses_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateMonthlyRecurrentExpenses) EXPECT() *CreateMonthlyRecurrentExpenses_Expecter {
	return &CreateMonthlyRecurrentExpenses_Expecter{mock: &_m.Mock}
}

// CreateMonthlyRecurrentExpenses provides a mock function with given fields: ctx
func (_m *CreateMonthlyRecurrentExpenses) CreateMonthlyRecurrentExpenses(ctx context.Context) (*recurrentexpenses.CreateMonthlyRecurrentExpensesOutput, error) {
	ret := _m.Called(ctx)

	var r0 *recurrentexpenses.CreateMonthlyRecurrentExpensesOutput
	if rf, ok := ret.Get(0).(func(context.Context) *recurrentexpenses.CreateMonthlyRecurrentExpensesOutput); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recurrentexpenses.CreateMonthlyRecurrentExpensesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateMonthlyRecurrentExpenses_CreateMonthlyRecurrentExpenses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMonthlyRecurrentExpenses'
type CreateMonthlyRecurrentExpenses_CreateMonthlyRecurrentExpenses_Call struct {
	*mock.Call
}

// CreateMonthlyRecurrentExpenses is a helper method to define mock.On call
//  - ctx context.Context
func (_e *CreateMonthlyRecurrentExpenses_Expecter) CreateMonthlyRecurrentExpenses(ctx interface{}) *CreateMonthlyRecurrentExpenses_CreateMonthlyRecurrentExpenses_Call {
	return &CreateMonthlyRecurrentExpenses_CreateMonthlyRecurrentExpenses_Call{Call: _e.mock.On("CreateMonthlyRecurrentExpenses", ctx)}
}

func (_c *CreateMonthlyRecurrentExpenses_CreateMonthlyRecurrentExpenses_Call) Run(run func(ctx context.Context)) *CreateMonthlyRecurrentExpenses_CreateMonthlyRecurrentExpenses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CreateMonthlyRecurrentExpenses_CreateMonthlyRecurrentExpenses_Call) Return(_a0 *recurrentexpenses.CreateMonthlyRecurrentExpensesOutput, _a1 error) *CreateMonthlyRecurrentExpenses_CreateMonthlyRecurrentExpenses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
