// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	recurrentexpenses "github.com/manicar2093/expenses_api/internal/recurrentexpenses"
	mock "github.com/stretchr/testify/mock"
)

// CreateRecurrentExpense is an autogenerated mock type for the CreateRecurrentExpense type
type CreateRecurrentExpense struct {
	mock.Mock
}

type CreateRecurrentExpense_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateRecurrentExpense) EXPECT() *CreateRecurrentExpense_Expecter {
	return &CreateRecurrentExpense_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, input
func (_m *CreateRecurrentExpense) Create(ctx context.Context, input *recurrentexpenses.CreateRecurrentExpenseInput) (*recurrentexpenses.CreateRecurrentExpenseOutput, error) {
	ret := _m.Called(ctx, input)

	var r0 *recurrentexpenses.CreateRecurrentExpenseOutput
	if rf, ok := ret.Get(0).(func(context.Context, *recurrentexpenses.CreateRecurrentExpenseInput) *recurrentexpenses.CreateRecurrentExpenseOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recurrentexpenses.CreateRecurrentExpenseOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *recurrentexpenses.CreateRecurrentExpenseInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRecurrentExpense_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CreateRecurrentExpense_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//  - ctx context.Context
//  - input *recurrentexpenses.CreateRecurrentExpenseInput
func (_e *CreateRecurrentExpense_Expecter) Create(ctx interface{}, input interface{}) *CreateRecurrentExpense_Create_Call {
	return &CreateRecurrentExpense_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *CreateRecurrentExpense_Create_Call) Run(run func(ctx context.Context, input *recurrentexpenses.CreateRecurrentExpenseInput)) *CreateRecurrentExpense_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*recurrentexpenses.CreateRecurrentExpenseInput))
	})
	return _c
}

func (_c *CreateRecurrentExpense_Create_Call) Return(_a0 *recurrentexpenses.CreateRecurrentExpenseOutput, _a1 error) *CreateRecurrentExpense_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
