// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	reports "github.com/manicar2093/expenses_api/internal/reports"
	mock "github.com/stretchr/testify/mock"
)

// CurrentMonthDetailsGettable is an autogenerated mock type for the CurrentMonthDetailsGettable type
type CurrentMonthDetailsGettable struct {
	mock.Mock
}

type CurrentMonthDetailsGettable_Expecter struct {
	mock *mock.Mock
}

func (_m *CurrentMonthDetailsGettable) EXPECT() *CurrentMonthDetailsGettable_Expecter {
	return &CurrentMonthDetailsGettable_Expecter{mock: &_m.Mock}
}

// GetCurrentMonthDetails provides a mock function with given fields: ctx
func (_m *CurrentMonthDetailsGettable) GetCurrentMonthDetails(ctx context.Context) (*reports.CurrentMonthDetailsOutput, error) {
	ret := _m.Called(ctx)

	var r0 *reports.CurrentMonthDetailsOutput
	if rf, ok := ret.Get(0).(func(context.Context) *reports.CurrentMonthDetailsOutput); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reports.CurrentMonthDetailsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CurrentMonthDetailsGettable_GetCurrentMonthDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentMonthDetails'
type CurrentMonthDetailsGettable_GetCurrentMonthDetails_Call struct {
	*mock.Call
}

// GetCurrentMonthDetails is a helper method to define mock.On call
//  - ctx context.Context
func (_e *CurrentMonthDetailsGettable_Expecter) GetCurrentMonthDetails(ctx interface{}) *CurrentMonthDetailsGettable_GetCurrentMonthDetails_Call {
	return &CurrentMonthDetailsGettable_GetCurrentMonthDetails_Call{Call: _e.mock.On("GetCurrentMonthDetails", ctx)}
}

func (_c *CurrentMonthDetailsGettable_GetCurrentMonthDetails_Call) Run(run func(ctx context.Context)) *CurrentMonthDetailsGettable_GetCurrentMonthDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CurrentMonthDetailsGettable_GetCurrentMonthDetails_Call) Return(_a0 *reports.CurrentMonthDetailsOutput, _a1 error) *CurrentMonthDetailsGettable_GetCurrentMonthDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
