// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	reports "github.com/manicar2093/expenses_api/internal/reports"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CurrentMonthDetailsGettable is an autogenerated mock type for the CurrentMonthDetailsGettable type
type CurrentMonthDetailsGettable struct {
	mock.Mock
}

type CurrentMonthDetailsGettable_Expecter struct {
	mock *mock.Mock
}

func (_m *CurrentMonthDetailsGettable) EXPECT() *CurrentMonthDetailsGettable_Expecter {
	return &CurrentMonthDetailsGettable_Expecter{mock: &_m.Mock}
}

// GetExpenses provides a mock function with given fields: ctx, userID
func (_m *CurrentMonthDetailsGettable) GetExpenses(ctx context.Context, userID uuid.UUID) (*reports.CurrentMonthDetailsOutput, error) {
	ret := _m.Called(ctx, userID)

	var r0 *reports.CurrentMonthDetailsOutput
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *reports.CurrentMonthDetailsOutput); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reports.CurrentMonthDetailsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CurrentMonthDetailsGettable_GetExpenses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpenses'
type CurrentMonthDetailsGettable_GetExpenses_Call struct {
	*mock.Call
}

// GetExpenses is a helper method to define mock.On call
//  - ctx context.Context
//  - userID uuid.UUID
func (_e *CurrentMonthDetailsGettable_Expecter) GetExpenses(ctx interface{}, userID interface{}) *CurrentMonthDetailsGettable_GetExpenses_Call {
	return &CurrentMonthDetailsGettable_GetExpenses_Call{Call: _e.mock.On("GetExpenses", ctx, userID)}
}

func (_c *CurrentMonthDetailsGettable_GetExpenses_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *CurrentMonthDetailsGettable_GetExpenses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CurrentMonthDetailsGettable_GetExpenses_Call) Return(_a0 *reports.CurrentMonthDetailsOutput, _a1 error) *CurrentMonthDetailsGettable_GetExpenses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
