// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/manicar2093/expenses_api/internal/entities"
	expenses "github.com/manicar2093/expenses_api/internal/expenses"

	mock "github.com/stretchr/testify/mock"
)

// ExpenseCreatable is an autogenerated mock type for the ExpenseCreatable type
type ExpenseCreatable struct {
	mock.Mock
}

type ExpenseCreatable_Expecter struct {
	mock *mock.Mock
}

func (_m *ExpenseCreatable) EXPECT() *ExpenseCreatable_Expecter {
	return &ExpenseCreatable_Expecter{mock: &_m.Mock}
}

// CreateExpense provides a mock function with given fields: _a0, _a1
func (_m *ExpenseCreatable) CreateExpense(_a0 context.Context, _a1 *expenses.CreateExpenseInput) (*entities.Expense, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *entities.Expense
	if rf, ok := ret.Get(0).(func(context.Context, *expenses.CreateExpenseInput) *entities.Expense); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Expense)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *expenses.CreateExpenseInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpenseCreatable_CreateExpense_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExpense'
type ExpenseCreatable_CreateExpense_Call struct {
	*mock.Call
}

// CreateExpense is a helper method to define mock.On call
//  - _a0 context.Context
//  - _a1 *expenses.CreateExpenseInput
func (_e *ExpenseCreatable_Expecter) CreateExpense(_a0 interface{}, _a1 interface{}) *ExpenseCreatable_CreateExpense_Call {
	return &ExpenseCreatable_CreateExpense_Call{Call: _e.mock.On("CreateExpense", _a0, _a1)}
}

func (_c *ExpenseCreatable_CreateExpense_Call) Run(run func(_a0 context.Context, _a1 *expenses.CreateExpenseInput)) *ExpenseCreatable_CreateExpense_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*expenses.CreateExpenseInput))
	})
	return _c
}

func (_c *ExpenseCreatable_CreateExpense_Call) Return(_a0 *entities.Expense, _a1 error) *ExpenseCreatable_CreateExpense_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
