// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/manicar2093/expenses_api/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// ExpensesPeriodicityService is an autogenerated mock type for the ExpensesPeriodicityService type
type ExpensesPeriodicityService struct {
	mock.Mock
}

type ExpensesPeriodicityService_Expecter struct {
	mock *mock.Mock
}

func (_m *ExpensesPeriodicityService) EXPECT() *ExpensesPeriodicityService_Expecter {
	return &ExpensesPeriodicityService_Expecter{mock: &_m.Mock}
}

// GenerateRecurrentExpensesByYearAndMonth provides a mock function with given fields: ctx, month, year
func (_m *ExpensesPeriodicityService) GenerateRecurrentExpensesByYearAndMonth(ctx context.Context, month uint, year uint) (*entities.RecurrentExpensesMonthlyCreated, error) {
	ret := _m.Called(ctx, month, year)

	var r0 *entities.RecurrentExpensesMonthlyCreated
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *entities.RecurrentExpensesMonthlyCreated); ok {
		r0 = rf(ctx, month, year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.RecurrentExpensesMonthlyCreated)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, month, year)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpensesPeriodicityService_GenerateRecurrentExpensesByYearAndMonth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRecurrentExpensesByYearAndMonth'
type ExpensesPeriodicityService_GenerateRecurrentExpensesByYearAndMonth_Call struct {
	*mock.Call
}

// GenerateRecurrentExpensesByYearAndMonth is a helper method to define mock.On call
//  - ctx context.Context
//  - month uint
//  - year uint
func (_e *ExpensesPeriodicityService_Expecter) GenerateRecurrentExpensesByYearAndMonth(ctx interface{}, month interface{}, year interface{}) *ExpensesPeriodicityService_GenerateRecurrentExpensesByYearAndMonth_Call {
	return &ExpensesPeriodicityService_GenerateRecurrentExpensesByYearAndMonth_Call{Call: _e.mock.On("GenerateRecurrentExpensesByYearAndMonth", ctx, month, year)}
}

func (_c *ExpensesPeriodicityService_GenerateRecurrentExpensesByYearAndMonth_Call) Run(run func(ctx context.Context, month uint, year uint)) *ExpensesPeriodicityService_GenerateRecurrentExpensesByYearAndMonth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *ExpensesPeriodicityService_GenerateRecurrentExpensesByYearAndMonth_Call) Return(_a0 *entities.RecurrentExpensesMonthlyCreated, _a1 error) *ExpensesPeriodicityService_GenerateRecurrentExpensesByYearAndMonth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
