// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	expenses "github.com/manicar2093/expenses_api/internal/expenses"
	mock "github.com/stretchr/testify/mock"
)

// ExpenseToPaidSetteable is an autogenerated mock type for the ExpenseToPaidSetteable type
type ExpenseToPaidSetteable struct {
	mock.Mock
}

type ExpenseToPaidSetteable_Expecter struct {
	mock *mock.Mock
}

func (_m *ExpenseToPaidSetteable) EXPECT() *ExpenseToPaidSetteable_Expecter {
	return &ExpenseToPaidSetteable_Expecter{mock: &_m.Mock}
}

// SetToPaid provides a mock function with given fields: ctx, input
func (_m *ExpenseToPaidSetteable) SetToPaid(ctx context.Context, input *expenses.SetExpenseToPaidInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *expenses.SetExpenseToPaidInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpenseToPaidSetteable_SetToPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetToPaid'
type ExpenseToPaidSetteable_SetToPaid_Call struct {
	*mock.Call
}

// SetToPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - input *expenses.SetExpenseToPaidInput
func (_e *ExpenseToPaidSetteable_Expecter) SetToPaid(ctx interface{}, input interface{}) *ExpenseToPaidSetteable_SetToPaid_Call {
	return &ExpenseToPaidSetteable_SetToPaid_Call{Call: _e.mock.On("SetToPaid", ctx, input)}
}

func (_c *ExpenseToPaidSetteable_SetToPaid_Call) Run(run func(ctx context.Context, input *expenses.SetExpenseToPaidInput)) *ExpenseToPaidSetteable_SetToPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*expenses.SetExpenseToPaidInput))
	})
	return _c
}

func (_c *ExpenseToPaidSetteable_SetToPaid_Call) Return(_a0 error) *ExpenseToPaidSetteable_SetToPaid_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewExpenseToPaidSetteable interface {
	mock.TestingT
	Cleanup(func())
}

// NewExpenseToPaidSetteable creates a new instance of ExpenseToPaidSetteable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExpenseToPaidSetteable(t mockConstructorTestingTNewExpenseToPaidSetteable) *ExpenseToPaidSetteable {
	mock := &ExpenseToPaidSetteable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
