// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/manicar2093/expenses_api/internal/entities"
	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"

	time "time"
)

// ExpensesRepository is an autogenerated mock type for the ExpensesRepository type
type ExpensesRepository struct {
	mock.Mock
}

type ExpensesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ExpensesRepository) EXPECT() *ExpensesRepository_Expecter {
	return &ExpensesRepository_Expecter{mock: &_m.Mock}
}

// FindByNameAndIsRecurrent provides a mock function with given fields: ctx, expenseName
func (_m *ExpensesRepository) FindByNameAndIsRecurrent(ctx context.Context, expenseName string) (*entities.Expense, error) {
	ret := _m.Called(ctx, expenseName)

	var r0 *entities.Expense
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Expense); ok {
		r0 = rf(ctx, expenseName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Expense)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, expenseName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpensesRepository_FindByNameAndIsRecurrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNameAndIsRecurrent'
type ExpensesRepository_FindByNameAndIsRecurrent_Call struct {
	*mock.Call
}

// FindByNameAndIsRecurrent is a helper method to define mock.On call
//  - ctx context.Context
//  - expenseName string
func (_e *ExpensesRepository_Expecter) FindByNameAndIsRecurrent(ctx interface{}, expenseName interface{}) *ExpensesRepository_FindByNameAndIsRecurrent_Call {
	return &ExpensesRepository_FindByNameAndIsRecurrent_Call{Call: _e.mock.On("FindByNameAndIsRecurrent", ctx, expenseName)}
}

func (_c *ExpensesRepository_FindByNameAndIsRecurrent_Call) Run(run func(ctx context.Context, expenseName string)) *ExpensesRepository_FindByNameAndIsRecurrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ExpensesRepository_FindByNameAndIsRecurrent_Call) Return(_a0 *entities.Expense, _a1 error) *ExpensesRepository_FindByNameAndIsRecurrent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetExpensesByMonth provides a mock function with given fields: ctx, month
func (_m *ExpensesRepository) GetExpensesByMonth(ctx context.Context, month time.Month) (*[]entities.Expense, error) {
	ret := _m.Called(ctx, month)

	var r0 *[]entities.Expense
	if rf, ok := ret.Get(0).(func(context.Context, time.Month) *[]entities.Expense); ok {
		r0 = rf(ctx, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entities.Expense)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, time.Month) error); ok {
		r1 = rf(ctx, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpensesRepository_GetExpensesByMonth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpensesByMonth'
type ExpensesRepository_GetExpensesByMonth_Call struct {
	*mock.Call
}

// GetExpensesByMonth is a helper method to define mock.On call
//  - ctx context.Context
//  - month time.Month
func (_e *ExpensesRepository_Expecter) GetExpensesByMonth(ctx interface{}, month interface{}) *ExpensesRepository_GetExpensesByMonth_Call {
	return &ExpensesRepository_GetExpensesByMonth_Call{Call: _e.mock.On("GetExpensesByMonth", ctx, month)}
}

func (_c *ExpensesRepository_GetExpensesByMonth_Call) Run(run func(ctx context.Context, month time.Month)) *ExpensesRepository_GetExpensesByMonth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Month))
	})
	return _c
}

func (_c *ExpensesRepository_GetExpensesByMonth_Call) Return(_a0 *[]entities.Expense, _a1 error) *ExpensesRepository_GetExpensesByMonth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Save provides a mock function with given fields: ctx, expense
func (_m *ExpensesRepository) Save(ctx context.Context, expense *entities.Expense) error {
	ret := _m.Called(ctx, expense)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Expense) error); ok {
		r0 = rf(ctx, expense)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpensesRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type ExpensesRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//  - ctx context.Context
//  - expense *entities.Expense
func (_e *ExpensesRepository_Expecter) Save(ctx interface{}, expense interface{}) *ExpensesRepository_Save_Call {
	return &ExpensesRepository_Save_Call{Call: _e.mock.On("Save", ctx, expense)}
}

func (_c *ExpensesRepository_Save_Call) Run(run func(ctx context.Context, expense *entities.Expense)) *ExpensesRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Expense))
	})
	return _c
}

func (_c *ExpensesRepository_Save_Call) Return(_a0 error) *ExpensesRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

// UpdateIsPaidByExpenseID provides a mock function with given fields: ctx, expenseID, status
func (_m *ExpensesRepository) UpdateIsPaidByExpenseID(ctx context.Context, expenseID primitive.ObjectID, status bool) error {
	ret := _m.Called(ctx, expenseID, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, bool) error); ok {
		r0 = rf(ctx, expenseID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpensesRepository_UpdateIsPaidByExpenseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIsPaidByExpenseID'
type ExpensesRepository_UpdateIsPaidByExpenseID_Call struct {
	*mock.Call
}

// UpdateIsPaidByExpenseID is a helper method to define mock.On call
//  - ctx context.Context
//  - expenseID primitive.ObjectID
//  - status bool
func (_e *ExpensesRepository_Expecter) UpdateIsPaidByExpenseID(ctx interface{}, expenseID interface{}, status interface{}) *ExpensesRepository_UpdateIsPaidByExpenseID_Call {
	return &ExpensesRepository_UpdateIsPaidByExpenseID_Call{Call: _e.mock.On("UpdateIsPaidByExpenseID", ctx, expenseID, status)}
}

func (_c *ExpensesRepository_UpdateIsPaidByExpenseID_Call) Run(run func(ctx context.Context, expenseID primitive.ObjectID, status bool)) *ExpensesRepository_UpdateIsPaidByExpenseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID), args[2].(bool))
	})
	return _c
}

func (_c *ExpensesRepository_UpdateIsPaidByExpenseID_Call) Return(_a0 error) *ExpensesRepository_UpdateIsPaidByExpenseID_Call {
	_c.Call.Return(_a0)
	return _c
}
