// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	recurrentexpenses "github.com/manicar2093/expenses_api/internal/recurrentexpenses"
	mock "github.com/stretchr/testify/mock"
)

// GetAllRecurrentExpenses is an autogenerated mock type for the GetAllRecurrentExpenses type
type GetAllRecurrentExpenses struct {
	mock.Mock
}

type GetAllRecurrentExpenses_Expecter struct {
	mock *mock.Mock
}

func (_m *GetAllRecurrentExpenses) EXPECT() *GetAllRecurrentExpenses_Expecter {
	return &GetAllRecurrentExpenses_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function with given fields: ctx
func (_m *GetAllRecurrentExpenses) GetAll(ctx context.Context) (*recurrentexpenses.GetAllRecurrentExpensesOutput, error) {
	ret := _m.Called(ctx)

	var r0 *recurrentexpenses.GetAllRecurrentExpensesOutput
	if rf, ok := ret.Get(0).(func(context.Context) *recurrentexpenses.GetAllRecurrentExpensesOutput); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recurrentexpenses.GetAllRecurrentExpensesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllRecurrentExpenses_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type GetAllRecurrentExpenses_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//  - ctx context.Context
func (_e *GetAllRecurrentExpenses_Expecter) GetAll(ctx interface{}) *GetAllRecurrentExpenses_GetAll_Call {
	return &GetAllRecurrentExpenses_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *GetAllRecurrentExpenses_GetAll_Call) Run(run func(ctx context.Context)) *GetAllRecurrentExpenses_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *GetAllRecurrentExpenses_GetAll_Call) Return(_a0 *recurrentexpenses.GetAllRecurrentExpensesOutput, _a1 error) *GetAllRecurrentExpenses_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
