// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	auth "github.com/manicar2093/expenses_api/internal/auth"
	mock "github.com/stretchr/testify/mock"
)

// LoginableByToken is an autogenerated mock type for the LoginableByToken type
type LoginableByToken struct {
	mock.Mock
}

type LoginableByToken_Expecter struct {
	mock *mock.Mock
}

func (_m *LoginableByToken) EXPECT() *LoginableByToken_Expecter {
	return &LoginableByToken_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: token
func (_m *LoginableByToken) Login(token string) (*auth.LoginOutput, error) {
	ret := _m.Called(token)

	var r0 *auth.LoginOutput
	if rf, ok := ret.Get(0).(func(string) *auth.LoginOutput); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.LoginOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginableByToken_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type LoginableByToken_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//  - token string
func (_e *LoginableByToken_Expecter) Login(token interface{}) *LoginableByToken_Login_Call {
	return &LoginableByToken_Login_Call{Call: _e.mock.On("Login", token)}
}

func (_c *LoginableByToken_Login_Call) Run(run func(token string)) *LoginableByToken_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *LoginableByToken_Login_Call) Return(_a0 *auth.LoginOutput, _a1 error) *LoginableByToken_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
