// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// Middlewares is an autogenerated mock type for the Middlewares type
type Middlewares struct {
	mock.Mock
}

type Middlewares_Expecter struct {
	mock *mock.Mock
}

func (_m *Middlewares) EXPECT() *Middlewares_Expecter {
	return &Middlewares_Expecter{mock: &_m.Mock}
}

// LoggedIn provides a mock function with given fields: next
func (_m *Middlewares) LoggedIn(next echo.HandlerFunc) echo.HandlerFunc {
	ret := _m.Called(next)

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func(echo.HandlerFunc) echo.HandlerFunc); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// Middlewares_LoggedIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoggedIn'
type Middlewares_LoggedIn_Call struct {
	*mock.Call
}

// LoggedIn is a helper method to define mock.On call
//   - next echo.HandlerFunc
func (_e *Middlewares_Expecter) LoggedIn(next interface{}) *Middlewares_LoggedIn_Call {
	return &Middlewares_LoggedIn_Call{Call: _e.mock.On("LoggedIn", next)}
}

func (_c *Middlewares_LoggedIn_Call) Run(run func(next echo.HandlerFunc)) *Middlewares_LoggedIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.HandlerFunc))
	})
	return _c
}

func (_c *Middlewares_LoggedIn_Call) Return(_a0 echo.HandlerFunc) *Middlewares_LoggedIn_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewMiddlewares interface {
	mock.TestingT
	Cleanup(func())
}

// NewMiddlewares creates a new instance of Middlewares. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMiddlewares(t mockConstructorTestingTNewMiddlewares) *Middlewares {
	mock := &Middlewares{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
