// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	recurrentexpenses "github.com/manicar2093/expenses_api/internal/recurrentexpenses"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// RecurrentExpensesAllGettable is an autogenerated mock type for the RecurrentExpensesAllGettable type
type RecurrentExpensesAllGettable struct {
	mock.Mock
}

type RecurrentExpensesAllGettable_Expecter struct {
	mock *mock.Mock
}

func (_m *RecurrentExpensesAllGettable) EXPECT() *RecurrentExpensesAllGettable_Expecter {
	return &RecurrentExpensesAllGettable_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function with given fields: ctx, userID
func (_m *RecurrentExpensesAllGettable) GetAll(ctx context.Context, userID uuid.UUID) (*recurrentexpenses.GetAllRecurrentExpensesOutput, error) {
	ret := _m.Called(ctx, userID)

	var r0 *recurrentexpenses.GetAllRecurrentExpensesOutput
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *recurrentexpenses.GetAllRecurrentExpensesOutput); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recurrentexpenses.GetAllRecurrentExpensesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecurrentExpensesAllGettable_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type RecurrentExpensesAllGettable_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//  - ctx context.Context
//  - userID uuid.UUID
func (_e *RecurrentExpensesAllGettable_Expecter) GetAll(ctx interface{}, userID interface{}) *RecurrentExpensesAllGettable_GetAll_Call {
	return &RecurrentExpensesAllGettable_GetAll_Call{Call: _e.mock.On("GetAll", ctx, userID)}
}

func (_c *RecurrentExpensesAllGettable_GetAll_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *RecurrentExpensesAllGettable_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *RecurrentExpensesAllGettable_GetAll_Call) Return(_a0 *recurrentexpenses.GetAllRecurrentExpensesOutput, _a1 error) *RecurrentExpensesAllGettable_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
