// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/manicar2093/expenses_api/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// SessionCreateable is an autogenerated mock type for the SessionCreateable type
type SessionCreateable struct {
	mock.Mock
}

type SessionCreateable_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionCreateable) EXPECT() *SessionCreateable_Expecter {
	return &SessionCreateable_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, session
func (_m *SessionCreateable) Create(ctx context.Context, session *entities.Session) error {
	ret := _m.Called(ctx, session)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionCreateable_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionCreateable_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *entities.Session
func (_e *SessionCreateable_Expecter) Create(ctx interface{}, session interface{}) *SessionCreateable_Create_Call {
	return &SessionCreateable_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *SessionCreateable_Create_Call) Run(run func(ctx context.Context, session *entities.Session)) *SessionCreateable_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Session))
	})
	return _c
}

func (_c *SessionCreateable_Create_Call) Return(_a0 error) *SessionCreateable_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewSessionCreateable interface {
	mock.TestingT
	Cleanup(func())
}

// NewSessionCreateable creates a new instance of SessionCreateable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSessionCreateable(t mockConstructorTestingTNewSessionCreateable) *SessionCreateable {
	mock := &SessionCreateable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
