// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StructValidable is an autogenerated mock type for the StructValidable type
type StructValidable struct {
	mock.Mock
}

type StructValidable_Expecter struct {
	mock *mock.Mock
}

func (_m *StructValidable) EXPECT() *StructValidable_Expecter {
	return &StructValidable_Expecter{mock: &_m.Mock}
}

// ValidateStruct provides a mock function with given fields: toValidate
func (_m *StructValidable) ValidateStruct(toValidate interface{}) error {
	ret := _m.Called(toValidate)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(toValidate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StructValidable_ValidateStruct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateStruct'
type StructValidable_ValidateStruct_Call struct {
	*mock.Call
}

// ValidateStruct is a helper method to define mock.On call
//  - toValidate interface{}
func (_e *StructValidable_Expecter) ValidateStruct(toValidate interface{}) *StructValidable_ValidateStruct_Call {
	return &StructValidable_ValidateStruct_Call{Call: _e.mock.On("ValidateStruct", toValidate)}
}

func (_c *StructValidable_ValidateStruct_Call) Run(run func(toValidate interface{})) *StructValidable_ValidateStruct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *StructValidable_ValidateStruct_Call) Return(_a0 error) *StructValidable_ValidateStruct_Call {
	_c.Call.Return(_a0)
	return _c
}
