// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TimeMonthModifier is an autogenerated mock type for the TimeMonthModifier type
type TimeMonthModifier struct {
	mock.Mock
}

type TimeMonthModifier_Expecter struct {
	mock *mock.Mock
}

func (_m *TimeMonthModifier) EXPECT() *TimeMonthModifier_Expecter {
	return &TimeMonthModifier_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewTimeMonthModifier interface {
	mock.TestingT
	Cleanup(func())
}

// NewTimeMonthModifier creates a new instance of TimeMonthModifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTimeMonthModifier(t mockConstructorTestingTNewTimeMonthModifier) *TimeMonthModifier {
	mock := &TimeMonthModifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
