// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TimeMonthModifier is an autogenerated mock type for the TimeMonthModifier type
type TimeMonthModifier struct {
	mock.Mock
}

type TimeMonthModifier_Expecter struct {
	mock *mock.Mock
}

func (_m *TimeMonthModifier) EXPECT() *TimeMonthModifier_Expecter {
	return &TimeMonthModifier_Expecter{mock: &_m.Mock}
}
