// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// TokenRefreshable is an autogenerated mock type for the TokenRefreshable type
type TokenRefreshable struct {
	mock.Mock
}

type TokenRefreshable_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenRefreshable) EXPECT() *TokenRefreshable_Expecter {
	return &TokenRefreshable_Expecter{mock: &_m.Mock}
}

// RefreshToken provides a mock function with given fields: sessionID
func (_m *TokenRefreshable) RefreshToken(sessionID uuid.UUID) (string, error) {
	ret := _m.Called(sessionID)

	var r0 string
	if rf, ok := ret.Get(0).(func(uuid.UUID) string); ok {
		r0 = rf(sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenRefreshable_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type TokenRefreshable_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//  - sessionID uuid.UUID
func (_e *TokenRefreshable_Expecter) RefreshToken(sessionID interface{}) *TokenRefreshable_RefreshToken_Call {
	return &TokenRefreshable_RefreshToken_Call{Call: _e.mock.On("RefreshToken", sessionID)}
}

func (_c *TokenRefreshable_RefreshToken_Call) Run(run func(sessionID uuid.UUID)) *TokenRefreshable_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *TokenRefreshable_RefreshToken_Call) Return(_a0 string, _a1 error) *TokenRefreshable_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
