// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TokenRefreshable is an autogenerated mock type for the TokenRefreshable type
type TokenRefreshable struct {
	mock.Mock
}

type TokenRefreshable_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenRefreshable) EXPECT() *TokenRefreshable_Expecter {
	return &TokenRefreshable_Expecter{mock: &_m.Mock}
}

// RefreshToken provides a mock function with given fields: refreshToken
func (_m *TokenRefreshable) RefreshToken(refreshToken string) (string, error) {
	ret := _m.Called(refreshToken)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenRefreshable_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type TokenRefreshable_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//  - refreshToken string
func (_e *TokenRefreshable_Expecter) RefreshToken(refreshToken interface{}) *TokenRefreshable_RefreshToken_Call {
	return &TokenRefreshable_RefreshToken_Call{Call: _e.mock.On("RefreshToken", refreshToken)}
}

func (_c *TokenRefreshable_RefreshToken_Call) Run(run func(refreshToken string)) *TokenRefreshable_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TokenRefreshable_RefreshToken_Call) Return(_a0 string, _a1 error) *TokenRefreshable_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
