// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TokenValidable is an autogenerated mock type for the TokenValidable type
type TokenValidable struct {
	mock.Mock
}

type TokenValidable_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenValidable) EXPECT() *TokenValidable_Expecter {
	return &TokenValidable_Expecter{mock: &_m.Mock}
}

// ValidateToken provides a mock function with given fields: token
func (_m *TokenValidable) ValidateToken(token string) error {
	ret := _m.Called(token)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TokenValidable_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type TokenValidable_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//  - token string
func (_e *TokenValidable_Expecter) ValidateToken(token interface{}) *TokenValidable_ValidateToken_Call {
	return &TokenValidable_ValidateToken_Call{Call: _e.mock.On("ValidateToken", token)}
}

func (_c *TokenValidable_ValidateToken_Call) Run(run func(token string)) *TokenValidable_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TokenValidable_ValidateToken_Call) Return(_a0 error) *TokenValidable_ValidateToken_Call {
	_c.Call.Return(_a0)
	return _c
}
