// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	auth "github.com/manicar2093/expenses_api/internal/auth"
	mock "github.com/stretchr/testify/mock"
)

// Tokenizable is an autogenerated mock type for the Tokenizable type
type Tokenizable struct {
	mock.Mock
}

type Tokenizable_Expecter struct {
	mock *mock.Mock
}

func (_m *Tokenizable) EXPECT() *Tokenizable_Expecter {
	return &Tokenizable_Expecter{mock: &_m.Mock}
}

// CreateAccessToken provides a mock function with given fields: tokenDetails
func (_m *Tokenizable) CreateAccessToken(tokenDetails *auth.AccessToken) (string, error) {
	ret := _m.Called(tokenDetails)

	var r0 string
	if rf, ok := ret.Get(0).(func(*auth.AccessToken) string); ok {
		r0 = rf(tokenDetails)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*auth.AccessToken) error); ok {
		r1 = rf(tokenDetails)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Tokenizable_CreateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccessToken'
type Tokenizable_CreateAccessToken_Call struct {
	*mock.Call
}

// CreateAccessToken is a helper method to define mock.On call
//  - tokenDetails *auth.AccessToken
func (_e *Tokenizable_Expecter) CreateAccessToken(tokenDetails interface{}) *Tokenizable_CreateAccessToken_Call {
	return &Tokenizable_CreateAccessToken_Call{Call: _e.mock.On("CreateAccessToken", tokenDetails)}
}

func (_c *Tokenizable_CreateAccessToken_Call) Run(run func(tokenDetails *auth.AccessToken)) *Tokenizable_CreateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*auth.AccessToken))
	})
	return _c
}

func (_c *Tokenizable_CreateAccessToken_Call) Return(_a0 string, _a1 error) *Tokenizable_CreateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// CreateRefreshToken provides a mock function with given fields: tokenDetails
func (_m *Tokenizable) CreateRefreshToken(tokenDetails *auth.RefreshToken) (string, error) {
	ret := _m.Called(tokenDetails)

	var r0 string
	if rf, ok := ret.Get(0).(func(*auth.RefreshToken) string); ok {
		r0 = rf(tokenDetails)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*auth.RefreshToken) error); ok {
		r1 = rf(tokenDetails)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Tokenizable_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type Tokenizable_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//  - tokenDetails *auth.RefreshToken
func (_e *Tokenizable_Expecter) CreateRefreshToken(tokenDetails interface{}) *Tokenizable_CreateRefreshToken_Call {
	return &Tokenizable_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", tokenDetails)}
}

func (_c *Tokenizable_CreateRefreshToken_Call) Run(run func(tokenDetails *auth.RefreshToken)) *Tokenizable_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*auth.RefreshToken))
	})
	return _c
}

func (_c *Tokenizable_CreateRefreshToken_Call) Return(_a0 string, _a1 error) *Tokenizable_CreateRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ValidateToken provides a mock function with given fields: token
func (_m *Tokenizable) ValidateToken(token string) error {
	ret := _m.Called(token)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Tokenizable_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type Tokenizable_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//  - token string
func (_e *Tokenizable_Expecter) ValidateToken(token interface{}) *Tokenizable_ValidateToken_Call {
	return &Tokenizable_ValidateToken_Call{Call: _e.mock.On("ValidateToken", token)}
}

func (_c *Tokenizable_ValidateToken_Call) Run(run func(token string)) *Tokenizable_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Tokenizable_ValidateToken_Call) Return(_a0 error) *Tokenizable_ValidateToken_Call {
	_c.Call.Return(_a0)
	return _c
}
