// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/manicar2093/expenses_api/internal/auth"

	mock "github.com/stretchr/testify/mock"
)

// UserByEmailGettable is an autogenerated mock type for the UserByEmailGettable type
type UserByEmailGettable struct {
	mock.Mock
}

type UserByEmailGettable_Expecter struct {
	mock *mock.Mock
}

func (_m *UserByEmailGettable) EXPECT() *UserByEmailGettable_Expecter {
	return &UserByEmailGettable_Expecter{mock: &_m.Mock}
}

// FindUserByEmail provides a mock function with given fields: ctx, email
func (_m *UserByEmailGettable) FindUserByEmail(ctx context.Context, email string) (*auth.UserData, error) {
	ret := _m.Called(ctx, email)

	var r0 *auth.UserData
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.UserData); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.UserData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserByEmailGettable_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type UserByEmailGettable_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserByEmailGettable_Expecter) FindUserByEmail(ctx interface{}, email interface{}) *UserByEmailGettable_FindUserByEmail_Call {
	return &UserByEmailGettable_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", ctx, email)}
}

func (_c *UserByEmailGettable_FindUserByEmail_Call) Run(run func(ctx context.Context, email string)) *UserByEmailGettable_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserByEmailGettable_FindUserByEmail_Call) Return(_a0 *auth.UserData, _a1 error) *UserByEmailGettable_FindUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewUserByEmailGettable interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserByEmailGettable creates a new instance of UserByEmailGettable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserByEmailGettable(t mockConstructorTestingTNewUserByEmailGettable) *UserByEmailGettable {
	mock := &UserByEmailGettable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
