// Code generated by "stringer -type=Periodicity"; DO NOT EDIT.

package periodicity

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Daily-1]
	_ = x[Weekly-2]
	_ = x[FourteenDays-3]
	_ = x[Paydaily-4]
	_ = x[Monthly-5]
	_ = x[BiMonthly-6]
	_ = x[FourMonthly-7]
	_ = x[SixMonthly-8]
	_ = x[Yearly-9]
}

const _Periodicity_name = "DailyWeeklyFourteenDaysPaydailyMonthlyBiMonthlyFourMonthlySixMonthlyYearly"

var _Periodicity_index = [...]uint8{0, 5, 11, 23, 31, 38, 47, 58, 68, 74}

func (i Periodicity) String() string {
	i -= 1
	if i >= Periodicity(len(_Periodicity_index)-1) {
		return "Periodicity(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Periodicity_name[_Periodicity_index[i]:_Periodicity_index[i+1]]
}
